---


- name: Synchronize time for all hosts
  hosts: kolla
  gather_facts: false
  vars_files:
    - "roles/docker/defaults/main.yml"
  strategy: not_run_all
  #  serial: 1
  roles:
    - synchronize-time
  tags: time

#- name: config docker registry
#  hosts: kolla
#  roles:
#    - docker
